services:
  playwright:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspaces
    environment:
      NODE_ENV: development
    ports:
      - "3838:3838"
    user: "vscode"
    depends_on:
      - postgres

  # If you want to use a database, uncomment the following block

  # postgres:
  #   image: postgres:latest
  #   environment:
  #     POSTGRES_PASSWORD: postgres
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - ../.docker/postgresql/volumes:/var/lib/postgresql
